#!/usr/bin/ruby -w
print "Content-type: text/html\n\n";

puts "       <h2> Performance Registration </h2>";
puts "         <div id=\"content-left\">";
puts "           <form action=\"assign13.rb\">";
puts "             <h3>Please enter your information</h3>";
puts "             <label>Performance Type: </label>";
puts "             <select name=\"performance\" onchange=\"duet()\">";
puts "               <option value=\"solo\">Solo</option>";
puts "               <option value=\"duet\">Duet</option>";
puts "               <option value=\"concerto\">Concerto</option>";
puts "             </select><br/>";
puts "             <label>First Name: </label>";
puts "             <input type=\"text\" name=\"fname\"maxlength=\"15\" ";
puts "                    required=\"required\" autofocus=\"autofocus\" placeholder=\"Jane\"";
puts "                    id=\"fname\" onchange=\"validateFname();\">";
puts "                    <span class=\"error\" id=\"errorfname\">*Letters Only</span><br/>";
puts "             <label>Last Name: </label>";
puts "             <input type=\"text\" name=\"lname\" ";
puts "                    maxlength=\"15\" required=\"required\" ";
puts "                    placeholder=\"Smith\" id=\"lname\" onchange=\"validateLname();\">";
puts "                    <span class=\"error\" id=\"errorlname\">*Letters Only</span><br/>";
puts "             <label>Student ID: </label>";
puts "             <input type=\"text\" name=\"id\" maxlength=\"11\"";
puts "                    required=\"required\" placeholder=\"12-345-6789\"";
puts "                    id=\"id\" onchange=\"validateId();\">";
puts "                    <span class=\"error\" id=\"errorid\">*11-111-1111</span><br/>";
puts " ";
puts "             <div id=\"secondStudent\">";
puts "               <h3>Second Student for Duet</h3>";
puts "               <label>First Name: </label>";
puts "               <input type=\"text\" name=\"fname2\"";
puts "                      maxlength=\"15\" placeholder=\"John\"";
puts "                      id=\"fname2\" onchange=\"validateFname2();\">";
puts "                      <span class=\"error\" id=\"errorfname2\">*Letters Only</span><br/>";
puts "               <label>Last Name: </label>";
puts "               <input type=\"text\" name=\"lname2\" ";
puts "                      maxlength=\"15\" placeholder=\"Doe\"";
puts "                      id=\"lname2\" onchange=\"validateLname2();\">";
puts "                      <span class=\"error\" id=\"errorlname2\">*Letters Only</span><br/>";
puts "               <label>Student ID: </label>";
puts "               <input type=\"text\" name=\"id2\" ";
puts "                      maxlength=\"11\" placeholder=\"12-345-6789\"";
puts "                      id=\"id2\" onchange=\"validateId2();\">";
puts "                      <span class=\"error\" id=\"errorid2\">*11-111-1111</span><br/>";
puts "             </div>";
puts " ";
puts "             <h3>Skill Level</h3>";
puts "             <span>Beginner</span><input type=\"radio\" name=\"skill\" value=\"beginner\" id=\"beginner\">";
puts "             <span>Intermediate</span><input type=\"radio\" name=\"skill\" value=\"intermediate\" id=\"intermediate\"><br/>";
puts "             <span>Pre-Advanced</span><input type=\"radio\" name=\"skill\" value=\"pre-advanced\" id=\"pre-advanced\">";
puts "             <span>Advanced</span><input type=\"radio\" name=\"skill\" value=\"advanced\" id=\"advanced\"><span class=\"error\" id=\"errorskill\">*Select one</span><br/>";
puts "             <h3>Instrument</h3>";
puts "             Piano  <input type=\"radio\" name=\"instrument\" value=\"piano\"";
puts "                     id=\"piano\">";
puts "             Voice  <input type=\"radio\" name=\"instrument\" value=\"voice\"";
puts "                     id=\"voice\"><br/>";
puts "             String <input type=\"radio\" name=\"instrument\" value=\"string\"";
puts "                     id=\"string\">";
puts "             Organ  <input type=\"radio\" name=\"instrument\" value=\"organ\"";
puts "                     id=\"prgan\">";
puts "             Other  <input type=\"radio\" name=\"instrument\" value=\"other\"";
puts "                     id=\"other\"><span class=\"error\" id=\"errorinstrument\">*Select one</span><br/>";
puts "             <label>Location: </label>";
puts "             <select name=\"location\">";
puts "               <option value=\"Snow\">Snow</option>";
puts "               <option value=\"Kirkham\">Kirkham</option>";
puts "               <option value=\"MC\">Manwaring Center</option>";
puts "               <option value=\"Hart\">Hart</option>";
puts "             </select><br/>";
puts "             <label>Room #: </label>";
puts "             <input type=\"text\" name=\"room\" id=\"room\" ";
puts "             maxlength=\"5\" style=\"width:50px;\" ";
puts "             onchange=\"validateRoom();\">";
puts "                    <span class=\"error\" id=\"errorroom\">*100 321A etc</span><br/>";
puts "             <label>Time Slot: </label>";
puts "             <select name=\"time\">";
puts "               <option value=\"10:00am\">10:00am</option>";
puts "               <option value=\"10:30am\">10:30am</option>";
puts "               <option value=\"11:00am\">11:00am</option>";
puts "               <option value=\"11:30am\">11:30am</option>";
puts "               <option value=\"12:00pm\">12:00pm</option>";
puts "               <option value=\"12:30pm\">12:30pm</option>";
puts "               <option value=\"01:00pm\">01:00pm</option>";
puts "               <option value=\"01:30pm\">01:30pm</option>";
puts "               <option value=\"02:00pm\">02:00pm</option>";
puts "               <option value=\"02:30pm\">02:30pm</option>";
puts "             </select><br/>";
puts "             <input type=\"button\" value=\"Submit\" onclick=\"validateAll();\">";
puts "             <input type=\"reset\">";
puts "           </form>";
puts "         </div>";
puts "         <div id=\"content-right\">";
puts "         <h3>Registered Performers</h3>";
puts "           <div id=\"display\">";
puts "           </div>";
puts "         </div>";
puts "       </div>";
puts "<script>loadRegistered();</script>";
